name: Bedwars
main: ro.marius.bedwars.BedWarsPlugin
author: Marius
description: Bedwars Plugin by Marius
version: 1.5.8
api-version: 1.13
softdepend: [Citizens, SlimeWorldManager, FastAsyncWorldEdit, PlaceholderAPI, Multiverse, Multiverse-Core]